// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALsWjwbrph_ZAcnNnzUyeGQoCiYriTdJE',
    appId: '1:45545970584:web:809b408904a38aeacd29ed',
    messagingSenderId: '45545970584',
    projectId: 'event-app-77d2a',
    authDomain: 'event-app-77d2a.firebaseapp.com',
    storageBucket: 'event-app-77d2a.firebasestorage.app',
    measurementId: 'G-KQEM1WG3E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe8hpwgUSKWXZe6ATjnSnG2wlVHfDa8So',
    appId: '1:45545970584:android:b03bc4def8922b22cd29ed',
    messagingSenderId: '45545970584',
    projectId: 'event-app-77d2a',
    storageBucket: 'event-app-77d2a.firebasestorage.app',
  );
}
